services:
  db:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.db

    container_name: dhg503_db_container
    ports:
      - "54503:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dhg503
      POSTGRES_PASSWORD: dhg503dhg503
      POSTGRES_DB: dhg503
    healthcheck:
      test: >
        CMD-SHELL
        pg_isready -U dhg503 -d dhg503 -h localhost -p 5432 &&
        psql -U dhg503 -d dhg503 -c 'SELECT 1; SELECT pg_sleep(0.5); SELECT 1;'
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  pg_data:
